/**
 * Read-only audit of `public.agent_definitions` (service-role).
 *
 * Writes a markdown table to `docs/refactor/agent-avatar-state.md` covering every agent
 * definition row plus linked `public.users` snapshot fields. Flags rows where
 * `agent_definitions.avatar_url IS NULL` so the Phase 3 backfill migration can land with
 * PR-embedded evidence of the before/after state.
 *
 * Requires:
 *   SUPABASE_URL                — e.g. http://127.0.0.1:54321 (local) or https://<ref>.supabase.co
 *   SUPABASE_SERVICE_ROLE_KEY   — service_role key for the same project
 *
 * Usage:
 *   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... pnpm tsx scripts/audit-agent-avatars.ts
 *
 * IMPORTANT: this script performs NO writes. It is safe to run against production / staging.
 */

import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

/** Service-role script client — schema is not wired to `Database` here. */
type AuditSupabaseClient = SupabaseClient<any, 'public', 'public', any, any>;

type AgentDefRow = {
  id: string;
  slug: string;
  display_name: string;
  mention_handle: string;
  avatar_url: string | null;
  response_timeout_ms: number;
  auth_user_id: string;
  is_active: boolean;
  users: {
    id: string;
    avatar_url: string | null;
    is_agent: boolean | null;
  } | null;
};

function requireEnv(name: string): string {
  const v = process.env[name]?.trim();
  if (!v) {
    console.error(`Missing required environment variable: ${name}`);
    process.exit(1);
  }
  return v;
}

function mdEscape(value: string | null | undefined): string {
  if (value == null) return '`NULL`';
  if (value === '') return '`""`';
  // Pipe-safe + preserve backticks.
  return `\`${value.replace(/`/g, '\\`').replace(/\|/g, '\\|')}\``;
}

function mdBool(value: boolean | null | undefined): string {
  if (value == null) return '`NULL`';
  return value ? '`true`' : '`false`';
}

async function fetchAgents(supabase: AuditSupabaseClient): Promise<AgentDefRow[]> {
  const { data, error } = await supabase
    .from('agent_definitions')
    .select(
      'id, slug, display_name, mention_handle, avatar_url, response_timeout_ms, auth_user_id, is_active, users:auth_user_id ( id, avatar_url, is_agent )',
    )
    .order('slug', { ascending: true });

  if (error) {
    console.error('[audit-agent-avatars] agent_definitions query failed', error.message);
    process.exit(1);
  }
  return (data ?? []) as unknown as AgentDefRow[];
}

function buildMarkdown(rows: AgentDefRow[], supabaseUrl: string): string {
  const missingCount = rows.filter((r) => r.avatar_url == null || r.avatar_url === '').length;

  const header =
    '| slug | display_name | mention_handle | avatar_url | response_timeout_ms | auth_user_id | users.is_agent | users.avatar_url | ⚠️ |';
  const sep = '| --- | --- | --- | --- | --- | --- | --- | --- | --- |';

  const body = rows
    .map((r) => {
      const missingFlag = r.avatar_url == null || r.avatar_url === '' ? '🚩 NULL' : '';
      return [
        '',
        mdEscape(r.slug),
        mdEscape(r.display_name),
        mdEscape(r.mention_handle),
        mdEscape(r.avatar_url),
        `\`${r.response_timeout_ms}\``,
        mdEscape(r.auth_user_id),
        mdBool(r.users?.is_agent ?? null),
        mdEscape(r.users?.avatar_url ?? null),
        missingFlag,
        '',
      ]
        .join(' | ')
        .trim();
    })
    .join('\n');

  const host = (() => {
    try {
      return new URL(supabaseUrl).host;
    } catch {
      return supabaseUrl;
    }
  })();

  return [
    '# Agent Avatar State — Phase 3 Audit',
    '',
    `_Generated by \`scripts/audit-agent-avatars.ts\` against \`${host}\` on ${new Date().toISOString()}._`,
    '',
    `- Total agents: **${rows.length}**`,
    `- Rows with \`agent_definitions.avatar_url IS NULL\`: **${missingCount}** ${missingCount > 0 ? '🚩' : '✅'}`,
    '',
    '## `agent_definitions` joined with `public.users`',
    '',
    header,
    sep,
    body,
    '',
    '## How to interpret',
    '',
    '- The **⚠️** column flags rows the Phase 3 backfill migration will touch.',
    '- Compare `agent_definitions.avatar_url` to `users.avatar_url` to see whether the two sides of the avatar pipeline agree. The Phase 2 mapper rewrite now prefers `agent_definitions.avatar_url` for agent-authored messages (see `src/lib/agents/resolveAgentAvatar.ts`).',
    '- After the backfill lands, re-running this script should yield **0** flagged rows; only then should the NOT-NULL constraint migration apply.',
    '',
  ].join('\n');
}

async function main() {
  const url = requireEnv('SUPABASE_URL');
  const key = requireEnv('SUPABASE_SERVICE_ROLE_KEY');

  const supabase: AuditSupabaseClient = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const rows = await fetchAgents(supabase);
  const md = buildMarkdown(rows, url);

  const outPath = resolve(process.cwd(), 'docs/refactor/agent-avatar-state.md');
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, md, 'utf8');

  const missing = rows.filter((r) => r.avatar_url == null || r.avatar_url === '').length;
  console.log(`[audit-agent-avatars] ${rows.length} agents; ${missing} missing avatar_url.`);
  console.log(`[audit-agent-avatars] wrote ${outPath}`);
  if (missing > 0) {
    console.warn(
      '[audit-agent-avatars] 🚩 Some agents are missing avatar_url. Run the backfill migration before applying the NOT NULL constraint.',
    );
  }
}

main().catch((err) => {
  console.error('[audit-agent-avatars] unexpected failure', err);
  process.exit(1);
});
