/**
 * Generates stripe_plan_catalog seed SQL from live plan IDs + optional test catalog.
 *
 * Usage:
 *   pnpm run generate:stripe-plan-catalog-seed
 *   tsx scripts/generate-stripe-plan-catalog-seed.ts --include-test-example -o path.sql
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { STRIPE_PLAN_IDS_LIVE } from '../src/lib/stripe-plan-ids-live';
import type { StripePlanKey } from '../src/lib/stripe-plans';
import { STRIPE_PLAN_KEYS } from '../src/lib/stripe-plans';

type CatalogEntry = { productId: string; defaultPriceId?: string };

function parseArgs(argv: string[]): { outputPath: string | null; includeTestExample: boolean } {
  let outputPath: string | null = null;
  let includeTestExample = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '-o' || arg === '--output') {
      outputPath = argv[i + 1] ?? null;
      i++;
    } else if (arg === '--include-test-example') {
      includeTestExample = true;
    }
  }
  return { outputPath, includeTestExample };
}

function loadTestExampleCatalog(): Partial<Record<StripePlanKey, CatalogEntry>> {
  const path = resolve(
    dirname(fileURLToPath(import.meta.url)),
    '../docs/stripe-test-catalog-sandbox-fitness.example.json',
  );
  const raw = JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown>;
  const out: Partial<Record<StripePlanKey, CatalogEntry>> = {};
  for (const key of STRIPE_PLAN_KEYS) {
    const entry = raw[key];
    if (entry && typeof entry === 'object' && entry !== null && !Array.isArray(entry)) {
      const productId = (entry as Record<string, unknown>).productId;
      if (typeof productId === 'string' && productId.startsWith('prod_')) {
        out[key] = { productId };
      }
    }
  }
  return out;
}

function collectRows(
  includeTestExample: boolean,
): Array<{ stripe_product_id: string; plan_key: string }> {
  const byProductId = new Map<string, string>();

  for (const key of STRIPE_PLAN_KEYS) {
    const live = STRIPE_PLAN_IDS_LIVE[key];
    if (live?.productId) {
      byProductId.set(live.productId, key);
    }
  }

  if (includeTestExample) {
    const testCatalog = loadTestExampleCatalog();
    for (const key of STRIPE_PLAN_KEYS) {
      const test = testCatalog[key];
      if (test?.productId) {
        byProductId.set(test.productId, key);
      }
    }
  }

  return [...byProductId.entries()]
    .map(([stripe_product_id, plan_key]) => ({ stripe_product_id, plan_key }))
    .sort((a, b) => a.stripe_product_id.localeCompare(b.stripe_product_id));
}

function escapeSqlString(value: string): string {
  return value.replace(/'/g, "''");
}

function buildSql(rows: Array<{ stripe_product_id: string; plan_key: string }>): string {
  const header = `-- Generated by scripts/generate-stripe-plan-catalog-seed.ts — do not edit by hand.
-- Re-run after Stripe Dashboard product rotation:
--   pnpm run generate:stripe-plan-catalog-seed

`;

  if (rows.length === 0) {
    return `${header}-- No rows to seed.\n`;
  }

  const values = rows
    .map((r) => `  ('${escapeSqlString(r.stripe_product_id)}', '${escapeSqlString(r.plan_key)}')`)
    .join(',\n');

  return `${header}insert into public.stripe_plan_catalog (stripe_product_id, plan_key)
values
${values}
on conflict (stripe_product_id) do update
  set plan_key = excluded.plan_key;
`;
}

function main(): void {
  const { outputPath, includeTestExample } = parseArgs(process.argv.slice(2));
  const sql = buildSql(collectRows(includeTestExample));

  if (outputPath) {
    writeFileSync(resolve(outputPath), sql, 'utf8');
    process.stdout.write(`Wrote ${outputPath}\n`);
  } else {
    process.stdout.write(sql);
  }
}

main();
