-- Generated by scripts/generate-stripe-plan-catalog-seed.ts — do not edit by hand.
-- Re-run after Stripe Dashboard product rotation:
--   pnpm run generate:stripe-plan-catalog-seed
-- Copilot suggestion ignored: test athlete/host IDs merge via --include-test-example; studio-tier dev access requires catalog rows matching local workspace_subscriptions.stripe_product_id.

insert into public.stripe_plan_catalog (stripe_product_id, plan_key)
values
  ('prod_UDhTcM2fPV6Q5a', 'athlete'),
  ('prod_UE6nvKBLLeH6k6', 'host'),
  ('prod_UE6qKGg6mDMj9B', 'pro'),
  ('prod_UE6sc9yLpUp0Me', 'studio'),
  ('prod_UE6uvLSsz3mxKo', 'coach_pro'),
  ('prod_UEPent0XbfaD7J', 'studio_pro'),
  ('prod_UKNpmipizPpCpR', 'athlete'),
  ('prod_UKNqr5H1bGARE9', 'host')
on conflict (stripe_product_id) do update
  set plan_key = excluded.plan_key;
